import type { BlogPost } from '~~/models/BlogPost'
import type { Species } from '~~/models/Species'

/**
 * Fallback data shown when the backend API isn't available
 * (Vercel preview without backend, local dev without VEJ-API running, etc.)
 *
 * Slugs match the order/IDs so individual post/species pages can also
 * resolve them client-side via the same mocks.
 */

export const mockPosts: BlogPost[] = [
  {
    id: 'p-1',
    slug: 'el-arte-de-regar-sin-matar',
    title: 'El arte de regar sin matar',
    excerpt: 'Por qué la mitad de tus plantas mueren ahogadas, no de sed. Una guía práctica para leer la humedad del sustrato y entender los ritmos de cada especie.',
    image: 'https://images.unsplash.com/photo-1416879595882-3373a0480b5b?w=1200&q=80',
    category: 'Cuidados',
    publishedAt: '2026-04-12',
    author: { name: 'Ana M.', avatar: '' },
    content: [],
  } as any,
  {
    id: 'p-2',
    slug: 'monstera-anatomia-rebelde',
    title: 'Monstera: anatomía de una rebelde',
    excerpt: 'Por qué le salen agujeros, qué significan, y cómo provocar fenestración temprana en plantas jóvenes.',
    image: 'https://images.unsplash.com/photo-1614594975525-e45190c55d0b?w=1200&q=80',
    category: 'Especies',
    publishedAt: '2026-04-04',
    author: { name: 'Luis T.', avatar: '' },
    content: [],
  } as any,
  {
    id: 'p-3',
    slug: 'componer-con-plantas-regla-trio',
    title: 'Componer con plantas: la regla del trío',
    excerpt: 'Una técnica que floristas usan para arreglar cualquier rincón verde. Tres alturas, tres texturas, una conversación.',
    image: 'https://images.unsplash.com/photo-1485955900006-10f4d324d411?w=1200&q=80',
    category: 'Diseño',
    publishedAt: '2026-03-22',
    author: { name: 'Mar C.', avatar: '' },
    content: [],
  } as any,
  {
    id: 'p-4',
    slug: 'sustratos-recetas-basicas',
    title: 'Sustratos: tres recetas que cubren el 90% de tu jardín',
    excerpt: 'Olvídate de comprar mezclas pre-empacadas. Tres recetas con perlita, fibra de coco y lombricomposta que sirven para casi todo.',
    image: 'https://images.unsplash.com/photo-1466692476868-aef1dfb1e735?w=1200&q=80',
    category: 'Sustratos',
    publishedAt: '2026-03-08',
    author: { name: 'Ana M.', avatar: '' },
    content: [],
  } as any,
  {
    id: 'p-5',
    slug: 'plagas-comunes-soluciones-naturales',
    title: 'Plagas comunes y cómo combatirlas sin químicos',
    excerpt: 'Cochinilla, araña roja, mosca blanca. Identificación rápida y los remedios que sí funcionan en casa.',
    image: 'https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?w=1200&q=80',
    category: 'Cuidados',
    publishedAt: '2026-02-18',
    author: { name: 'Luis T.', avatar: '' },
    content: [],
  } as any,
  {
    id: 'p-6',
    slug: 'jardin-de-interior-poca-luz',
    title: 'Jardín de interior con poca luz: la lista corta',
    excerpt: 'Diez especies que toleran rincones oscuros, esquinas tristes y baños sin ventana. Probadas en casas reales.',
    image: 'https://images.unsplash.com/photo-1545241047-6083a3684587?w=1200&q=80',
    category: 'Especies',
    publishedAt: '2026-02-01',
    author: { name: 'Mar C.', avatar: '' },
    content: [],
  } as any,
]

export const mockFaqs: any[] = [
  { id: 'f1', category: 'Pedidos', question: '¿Cómo hago un pedido?', answer: 'Selecciona tu planta, agrégala al carrito y procede al checkout. Aceptamos tarjeta, transferencia y OXXO.' },
  { id: 'f2', category: 'Pedidos', question: '¿Puedo modificar mi pedido después de hacerlo?', answer: 'Sí, dentro de las primeras 4 horas. Después se prepara para envío y ya no se puede cambiar.' },
  { id: 'f3', category: 'Envíos', question: '¿Cuánto tarda mi envío?', answer: 'CDMX: 24-48h. Resto del país: 3-5 días. Foráneo: 5-8 días.' },
  { id: 'f4', category: 'Envíos', question: '¿Hacen envíos internacionales?', answer: 'Por ahora solo dentro de México. Pronto vendrán envíos a EUA y Centroamérica.' },
  { id: 'f5', category: 'Pagos', question: '¿Qué métodos de pago aceptan?', answer: 'Tarjetas (Visa, Mastercard, AMEX), transferencia SPEI, OXXO, PayPal y Mercado Pago.' },
  { id: 'f6', category: 'Pagos', question: '¿Es seguro pagar con tarjeta en su sitio?', answer: 'Sí. Usamos Stripe — tus datos nunca tocan nuestros servidores. Cumplimos PCI DSS.' },
  { id: 'f7', category: 'Plantas', question: '¿Cómo sé qué planta es para mí?', answer: 'Filtramos por dificultad, luz y riego en /species. También respondemos por contacto si necesitas ayuda.' },
  { id: 'f8', category: 'Plantas', question: '¿Qué hago si mi planta llega marchita?', answer: 'Mándanos foto en las primeras 48h. Si fue daño en envío, te mandamos otra sin costo.' },
  { id: 'f9', category: 'Plantas', question: '¿Las plantas son tóxicas para mascotas?', answer: 'Cada ficha de especie indica toxicidad. Filtra por "no tóxica" si tienes pets.' },
]

export const mockSpecies: Species[] = [
  {
    id: 's-1',
    slug: 'monstera-deliciosa',
    commonName: 'Monstera Deliciosa',
    scientificName: 'Monstera deliciosa',
    family: 'Araceae',
    image: 'https://images.unsplash.com/photo-1614594975525-e45190c55d0b?w=900&q=80',
    description: 'La rebelde de hoja perforada. Crece hacia donde le da la luz, no donde la pongas.',
    careLevel: 'easy',
    sunlight: 'medium',
    watering: 'medium',
    growthRate: 'fast',
    toxicity: 'pets',
  } as any,
  {
    id: 's-2',
    slug: 'ficus-lyrata',
    commonName: 'Ficus Lyrata',
    scientificName: 'Ficus lyrata',
    family: 'Moraceae',
    image: 'https://images.unsplash.com/photo-1545241047-6083a3684587?w=900&q=80',
    description: 'Hojas grandes en forma de violín. Quiere luz indirecta intensa y mucha paciencia.',
    careLevel: 'medium',
    sunlight: 'high',
    watering: 'medium',
    growthRate: 'medium',
    toxicity: 'pets',
  } as any,
  {
    id: 's-3',
    slug: 'calathea-orbifolia',
    commonName: 'Calathea Orbifolia',
    scientificName: 'Goeppertia orbifolia',
    family: 'Marantaceae',
    image: 'https://images.unsplash.com/photo-1632207691143-643e2a9a9361?w=900&q=80',
    description: 'Hojas catedrales con rayas plateadas. Reza al atardecer cerrando sus hojas.',
    careLevel: 'hard',
    sunlight: 'medium',
    watering: 'high',
    growthRate: 'slow',
    toxicity: 'none',
  } as any,
  {
    id: 's-4',
    slug: 'pothos-marble',
    commonName: 'Pothos Marble',
    scientificName: 'Epipremnum aureum',
    family: 'Araceae',
    image: 'https://images.unsplash.com/photo-1622383563227-04401ab4e5ea?w=900&q=80',
    description: 'Indestructible. Vive en cualquier rincón y perdona casi todos los olvidos.',
    careLevel: 'easy',
    sunlight: 'low',
    watering: 'low',
    growthRate: 'fast',
    toxicity: 'pets',
  } as any,
  {
    id: 's-5',
    slug: 'sansevieria-trifasciata',
    commonName: 'Sansevieria',
    scientificName: 'Dracaena trifasciata',
    family: 'Asparagaceae',
    image: 'https://images.unsplash.com/photo-1599598425947-5ad7d31f7d3a?w=900&q=80',
    description: 'Lengua de tigre. La planta de oficina por excelencia: aguanta lo que sea.',
    careLevel: 'easy',
    sunlight: 'low',
    watering: 'low',
    growthRate: 'slow',
    toxicity: 'pets',
  } as any,
  {
    id: 's-6',
    slug: 'alocasia-zebrina',
    commonName: 'Alocasia Zebrina',
    scientificName: 'Alocasia zebrina',
    family: 'Araceae',
    image: 'https://images.unsplash.com/photo-1632207691143-643e2a9a9361?w=900&q=80',
    description: 'Tallos rayados como cebra y hojas de flecha. Drama puro pero exigente.',
    careLevel: 'hard',
    sunlight: 'medium',
    watering: 'medium',
    growthRate: 'medium',
    toxicity: 'both',
  } as any,
  {
    id: 's-7',
    slug: 'philodendron-brasil',
    commonName: 'Philodendron Brasil',
    scientificName: 'Philodendron hederaceum',
    family: 'Araceae',
    image: 'https://images.unsplash.com/photo-1485955900006-10f4d324d411?w=900&q=80',
    description: 'Hojas con franjas amarillas como bandera brasileña. Crece rápido y feliz.',
    careLevel: 'easy',
    sunlight: 'medium',
    watering: 'medium',
    growthRate: 'fast',
    toxicity: 'pets',
  } as any,
  {
    id: 's-8',
    slug: 'strelitzia-nicolai',
    commonName: 'Strelitzia',
    scientificName: 'Strelitzia nicolai',
    family: 'Strelitziaceae',
    image: 'https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?w=900&q=80',
    description: 'Ave del paraíso gigante. Pide espacio, luz, y devuelve presencia.',
    careLevel: 'medium',
    sunlight: 'high',
    watering: 'medium',
    growthRate: 'medium',
    toxicity: 'pets',
  } as any,
]
